'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")>  _
Partial Friend NotInheritable Class ReglagePulve
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As ReglagePulve = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New ReglagePulve()),ReglagePulve)
    
    Public Shared ReadOnly Property [Default]() As ReglagePulve
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Valeur de test")>  _
    Public ReadOnly Property Test() As String
        Get
            Return CType(Me("Test"),String)
        End Get
    End Property
End Class
