'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
'à l'aide d'un outil, tel que ResGen ou Visual Studio.
'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
'avec l'option /str ou régénérez votre projet VS.
'''<summary>
'''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Resources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Crodip_agent.Resources", GetType(Resources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
    '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property _Exit() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Exit", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property add_to_favorites_96px() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("add_to_favorites_96px", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property AddTableHH() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("AddTableHH", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property arrow_refresh_small() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("arrow_refresh_small", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btn_annuler() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btn_annuler", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btn_annuler_200() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btn_annuler-200", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btn_annuler_250() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btn_annuler-250", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btn_delete() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btn_delete", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btn_divers_add() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btn_divers_add", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btn_divers_print() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btn_divers_print", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btn_empty() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btn_empty", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btn_empty_big() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btn_empty_big", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btn_fiche_voir() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btn_fiche_voir", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btn_login() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btn_login", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btn_refresh() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btn_refresh", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btn_retours() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btn_retours", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btn_search() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btn_search", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btn_Signture() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btn_Signture", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btn_suivant() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btn_suivant", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btn_suivantGrd() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btn_suivantGrd", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btn_valider() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btn_valider", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Button_Play_Icon_256() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Button_Play_Icon_256", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Button_PREVIous_Icon_256() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Button_PREVIous_Icon_256", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
    '''</summary>
    Friend Shared ReadOnly Property calculator() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("calculator", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property ClosePreviewHH() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ClosePreviewHH", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property delete() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property e_pulve_logo_blanc_bleu_1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("e-pulve-logo-blanc-bleu-1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Favorites() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Favorites", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property ico_crodipIndigo36() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ico_crodipIndigo36", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property ico_pdf() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ico_pdf", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
    '''</summary>
    Friend Shared ReadOnly Property Icon1() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("Icon1", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property icons8_membership_card() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("icons8_membership_card", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property jumelles16x16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("jumelles16x16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property login_bg() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("login_bg", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property login_bgcrodip() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("login_bgcrodip", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Login_bgcrodipIndigo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Login_bgcrodipIndigo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property login_bgVide() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("login_bgVide", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property logo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property logo_crodipIndigo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("logo_crodipIndigo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
    '''</summary>
    Friend Shared ReadOnly Property logoCRODIP() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("logoCRODIP", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property logoCRODIPIMG() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("logoCRODIPIMG", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property LogoMCII() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("LogoMCII", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property NavBackHS() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("NavBackHS", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Next36() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Next36", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property oeil16x16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("oeil16x16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property OeilBleu() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("OeilBleu", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Open36() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Open36", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PDF() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PDF", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property previous36() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("previous36", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property puce_h1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("puce_h1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property puce_h2() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("puce_h2", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PuceGriseT() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PuceGriseT", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PuceJauneT() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PuceJauneT", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PuceRougeT() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PuceRougeT", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PuceVerteT() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PuceVerteT", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
    '''</summary>
    Friend Shared ReadOnly Property pulveprinc() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("pulveprinc", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property save36() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("save36", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Start3() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Start3", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
    '''</summary>
    Friend Shared ReadOnly Property Transparent() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("Transparent", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
End Class
